[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "/plugins/netlify-plugin-stepzen"

[template]
  incoming-hooks = ["StepZen"]

[template.environment]
  STEPZEN_ENDPOINT = "Add your StepZen endpoint" 
  STEPZEN_ACCOUNT = "specifies the name of your StepZen account. This can be found on the My Account page on StepZen.com;"
  STEPZEN_ADMIN_KEY = "specifies the admin API Key that enables access to deploy APIs on your account on StepZen. This can be found on the My Account page on StepZen.com"
  STEPZEN_NAME = "specifies the endpoint name for your API. This will determine the URL that your endpoint will deployed to. For example, a user with the account name biggs and a endpoint name of my-api will deploy as https://biggs.stepzen.net/netlify/my-api/__graphql (note that this assumes the dealt STEPZEN_FOLDER value is used)."
